{% set python_min = '3.10.0' %}
{% set name = "arcx" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arcx-{{ version }}.tar.gz
  sha256: 7ffa32cf5f7ec50b61785ab0197ebc57151c335a49377c7469ed861e1e457b41

build:
  entry_points:
    - arcx = arcx.management:start_from_command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - click >=8.1.7,<9.0.0
    - pydantic >=2.8.2,<3.0.0
    - pytest >=8.3.2,<9.0.0
    - pytest-mock >=3.14.0,<4.0.0
    - pyyaml >=6.0.2,<7.0.0
    - rich >=13.7.1,<14.0.0

test:
  imports:
    - arcx
  commands:
    - pip check
    - arcx --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/arcx/
  summary: Archive (safe)-Removal Rolling Toolbox
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anto6715
